CREATE TYPE "public"."ProjectLocale" AS ENUM('pl', 'en');--> statement-breakpoint
CREATE TYPE "public"."ProjectStringType" AS ENUM('name', 'description', 'content');--> statement-breakpoint
CREATE TYPE "public"."ProjectType" AS ENUM('external', 'page', 'project');--> statement-breakpoint
CREATE TABLE "projects" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"url" text NOT NULL,
	"type" "ProjectType" DEFAULT 'project' NOT NULL,
	"themeCss" boolean DEFAULT false NOT NULL,
	"myQuery" boolean DEFAULT false NOT NULL,
	"published" boolean DEFAULT false NOT NULL,
	"order" smallint NOT NULL,
	"cover" text,
	CONSTRAINT "projects_slug_key" UNIQUE("url")
);
--> statement-breakpoint
CREATE TABLE "projects_strings" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_strings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"projectId" bigint,
	"locale" "ProjectLocale" NOT NULL,
	"type" "ProjectStringType" NOT NULL,
	"value" text
);
--> statement-breakpoint
ALTER TABLE "projects_strings" ADD CONSTRAINT "projects_strings_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;