"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.randomAnimal = exports.animals = void 0;
exports.animals = [
    'Dog',
    'Cat',
    'Cow',
    'Hen',
    'Sheep',
    'Rabbit',
    'Duck',
    'Horse',
    'Lama',
    'Pig',
    'Turkey',
    'Chicken',
    'Donkey',
    'Goat',
    'Guinea Pig',
    'Deer',
    'Fish',
    'Bee',
    'Goose',
    'Rat',
    'Giraffe',
    'Woodpecker',
    'Camel',
    'Starfish',
    'Koala',
    'Alligator',
    'Owl',
    'Tiger',
    'Bear',
    'Blue whale',
    'Coyote',
    'Chimpanzee',
    'Raccoon',
    'Lion',
    'Wolf',
    'Crocodile',
    'Dolphin',
    'Elephant',
    'Squirrel',
    'Snake',
    'Kangaroo',
    'Hippopotamus',
    'Elk',
    'Fox',
    'Gorilla',
    'Bat',
    'Hare',
    'Toad',
    'Frog',
    'Badger',
    'Lizard',
    'Mole',
    'Hedgehog',
    'Otter',
    'Reindeer',
    'Monkey',
    'Porcupine',
    'Leopard',
    'Cheetah',
    'Panda',
    'Rhinoceros',
    'Zebra',
    'Whale',
    'Octopus',
    'Shark',
    'Seahorse',
    'Jelly Fish',
    'Turtle',
    'Crab',
    'Clam',
    'Lobster',
    'Squid',
    'Shrimp',
    'Star Fish',
    'Swordfish',
    'Dugong',
    'Urchin',
    'Seal',
    'Walrus',
    'Sealion',
    'Pelican',
    'Oyster',
    'Manatee',
    'Lizards',
    'Jackrabbit',
    'Spiders',
    'Meerkats',
    'Scorpion',
    'Yucca Moth',
    'Sidewinder',
    'Saiga',
    'Bison',
    'Mule',
];
var randomAnimal = function () {
    return exports.animals[Math.floor(Math.random() * exports.animals.length)];
};
exports.randomAnimal = randomAnimal;
