import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import './globals.css';
import Head from 'next/head';
import {clsx} from 'clsx';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const font = Roboto({
    weight: ['400', '700'],
    subsets: ['latin', 'latin-ext'],
});

export default async function RootLayout({children}: PWC) {
    return (
        <html className={clsx('style-basic', font.className)}>
            <Head>
                <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
            </Head>
            <body>{children}</body>
        </html>
    );
}
