import type {Metadata} from 'next';

import {Roboto} from 'next/font/google';
import {clsx} from 'clsx';

import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: ['/favicon.ico'],
};

const font = Roboto({
    weight: ['400', '700'],
    subsets: ['latin', 'latin-ext'],
});

export default async function RootLayout({children}: PWC) {
    return (
        <html className={clsx('dark-scrollbars-compat dark', font.className)}>
            <body>{children}</body>
        </html>
    );
}
