import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import './globals.css';
import Layout from '@/ui/organisms/layout';
import Providers from '@/ui/organisms/providers';
import {getMessages} from 'next-intl/server';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const font = Roboto({
    weight: ['400', '700'],
    subsets: ['latin', 'latin-ext'],
});

type Props = {
    params: {
        locale: string;
    };
};

export default async function RootLayout({children, params}: PWC<Props>) {
    const messages = await getMessages();

    return (
        <Providers
            locale={params.locale}
            timeZone={'Europe/Warsaw'}
            messages={messages}
        >
            <Layout className={font.className} locale={params.locale}>
                {children}
            </Layout>
        </Providers>
    );
}
