// Seeds the database from `seed-data.json` (generated by
// `generate-seed-data.mjs` from a Supabase backup).
//
// Usage:
//   pnpm db:seed
//
// Requires DATABASE_URL in .env.local (loaded via `tsx --env-file`).

import {readFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

import {db} from '@/services/drizzle/drizzle-client';
import {
    ProjectInsert,
    ProjectStringInsert,
    projects,
    projectsStrings,
} from '@/services/drizzle/schema';

const here = dirname(fileURLToPath(import.meta.url));

type SeedData = {
    projects: ProjectInsert[];
    projectsStrings: ProjectStringInsert[];
};

function loadSeedData(): SeedData {
    const path = resolve(here, 'seed-data.json');
    try {
        return JSON.parse(readFileSync(path, 'utf8')) as SeedData;
    } catch {
        throw new Error(
            `Missing ${path} — generate it first:\n` +
                '  node scripts/seed/generate-seed-data.mjs <path-to-.backup>',
        );
    }
}

async function seed() {
    const data = loadSeedData();

    await db.transaction(async (tx) => {
        // Cascades to projects_strings via the FK, but be explicit anyway.
        await tx.delete(projectsStrings);
        await tx.delete(projects);

        if (data.projects.length > 0) {
            await tx.insert(projects).values(data.projects);
        }
        if (data.projectsStrings.length > 0) {
            await tx.insert(projectsStrings).values(data.projectsStrings);
        }
    });

    console.log(
        `Seeded ${data.projects.length} projects and ` +
            `${data.projectsStrings.length} project strings`,
    );
}

seed()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
