export type Project = {
    slug: string;
    name: string;
    description: string;
    css: Record<string, string>;
    globalCss: boolean;
    js: Record<string, string>;
    globalJs: boolean;
    date: string;
};

export const projects: Project[] = [
    {
        slug: 'animal',
        name: 'Animal',
        description: 'Animal animation',
        css: {'style.css': 'style.css'},
        globalCss: false,
        js: {'animal.js': 'animal.js'},
        globalJs: false,
        date: '2018-12-27',
    },
    {
        slug: 'animate',
        name: 'Animacja',
        description: 'Prosta animacja',
        css: {'animate.css': 'animate.css'},
        globalCss: false,
        js: {'animate.js': 'animate.js'},
        globalJs: true,
        date: '2015-05-22',
    },
    {
        slug: 'audio',
        name: 'Audio Visualizer 3D',
        description: '',
        css: {'audio.css': 'audio.css'},
        globalCss: false,
        js: {
            'glMatrix-0.9.5.min.js': 'glMatrix-0.9.5.min.js',
            'audio.js': 'audio.js',
        },
        globalJs: true,
        date: '2016-09-23',
    },
    {
        slug: 'billiards',
        name: 'Bilard',
        description: 'Bilard',
        css: {},
        globalCss: false,
        js: {'billiards.js': 'billiards.js'},
        globalJs: false,
        date: '2015-05-22',
    },
    {
        slug: 'canvas3d',
        name: 'Canvas 3D',
        description: 'Biblioteka 3d',
        css: {'canvas3d.css': 'canvas3d.css'},
        globalCss: false,
        js: {
            'object3d.js': 'object3d.js',
            'canvas3d.js': 'canvas3d.js',
            'demo3d.js': 'demo3d.js',
        },
        globalJs: false,
        date: '2016-09-27',
    },
    {
        slug: 'car3d',
        name: 'Car 3D model',
        description: 'Model samochodu ',
        css: {'car3D.css': 'car3D.css'},
        globalCss: false,
        js: {
            'three.min.three.min.js': 'three.min.three.min.js',
            'OBJLoader.js': 'OBJLoader.js',
            'car3D.js': 'car3D.js',
        },
        globalJs: false,
        date: '2016-02-12',
    },
    {
        slug: 'clock',
        name: 'Clock',
        description: 'Zegarek analogowy',
        css: {'clock.css': 'clock.css'},
        globalCss: false,
        js: {'clock.js': 'clock.js'},
        globalJs: false,
        date: '2015-11-13',
    },
    {
        slug: 'colorpicker',
        name: 'Kolor picker',
        description: '',
        css: {},
        globalCss: false,
        js: {'colorpicker.js': 'colorpicker.js', 'demo.js': 'demo.js'},
        globalJs: false,
        date: '2016-03-14',
    },
    {
        slug: 'draw',
        name: 'Paint',
        description: 'Internetowy paint',
        css: {'draw.css': 'draw.css'},
        globalCss: false,
        js: {'draw.js': 'draw.js'},
        globalJs: true,
        date: '2015-05-28',
    },
    {
        slug: 'drop',
        name: 'Drops',
        description: 'Ruch bąbelków',
        css: {'drop.css': 'drop.css'},
        globalCss: false,
        js: {'drop.js': 'drop.js'},
        globalJs: false,
        date: '2017-07-11',
    },
    {
        slug: 'flappy',
        name: 'Flappy Birds',
        description: 'Popularna gra flappy birds.',
        css: {'flappy.css': 'flappy.css'},
        globalCss: false,
        js: {'flappy-bird.js': 'flappy-bird.js'},
        globalJs: true,
        date: '2015-05-20',
    },
    {
        slug: 'gauss',
        name: 'Gauss',
        description: 'Rozkład liczb pseudolosowych',
        css: {'gauss.css': 'gauss.css'},
        globalCss: false,
        js: {'gauss.js': 'gauss.js'},
        globalJs: false,
        date: '2016-02-23',
    },
    {
        slug: 'graf',
        name: 'Graf',
        description: 'Grafik',
        css: {'graf.css': 'graf.css'},
        globalCss: false,
        js: {'graf.js': 'graf.js'},
        globalJs: false,
        date: '2016-06-02',
    },
    {
        slug: 'graph',
        name: 'Graph',
        description: 'Aplikacja rysująca wykresy',
        css: {'codemirror.css': 'codemirror.css', 'graph.css': 'graph.css'},
        globalCss: false,
        js: {
            'codemirror.js': 'codemirror.js',
            'graph.js': 'graph.js',
            'demoGraph.js': 'demoGraph.js',
        },
        globalJs: true,
        date: '2015-11-07',
    },
    {
        slug: 'grid',
        name: 'Particle',
        description: 'Cząstki oddziałujące z kursorem',
        css: {'grid.css': 'grid.css'},
        globalCss: false,
        js: {'grid.js': 'grid.js'},
        globalJs: false,
        date: '2017-06-28',
    },
    {
        slug: 'hangman',
        name: 'Wisielec',
        description: 'Gra wisielec',
        css: {'hangman.css': 'hangman.css'},
        globalCss: false,
        js: {'hangman.js': 'hangman.js'},
        globalJs: true,
        date: '2015-11-18',
    },
    {
        slug: 'jigsaw',
        name: 'Układanka',
        description: 'Układanka z zdjęcia',
        css: {'jigsaw.css': 'jigsaw.css'},
        globalCss: true,
        js: {'jigsaw.js': 'jigsaw.js'},
        globalJs: true,
        date: '2015-11-09',
    },
    {
        slug: 'jump',
        name: 'Jump',
        description: '-',
        css: {'jump.css': 'jump.css'},
        globalCss: false,
        js: {'jump.js': 'jump.js'},
        globalJs: false,
        date: '2016-02-20',
    },
    {
        slug: 'life',
        name: 'Gra w życie',
        description: '',
        css: {'life.css': 'life.css'},
        globalCss: true,
        js: {'life.js': 'life.js'},
        globalJs: true,
        date: '2016-10-02',
    },
    {
        slug: 'math',
        name: 'Wykresy ',
        description: 'Aplikacja do rysowania wykresu funkcji.',
        css: {'math.css': 'math.css', 'mathcode.css': 'mathcode.css'},
        globalCss: true,
        js: {'mathcode.js': 'mathcode.js', 'math.new.js': 'math.new.js'},
        globalJs: false,
        date: '2015-05-06',
    },
    {
        slug: 'mathcode',
        name: 'Math Code',
        description: 'Kod funckcji',
        css: {'mathcode.css': 'mathcode.css'},
        globalCss: false,
        js: {'mathcode.js': 'mathcode.js', 'demo.js': 'demo.js'},
        globalJs: false,
        date: '2016-03-10',
    },
    {
        slug: 'md5',
        name: 'Md5 Generator',
        description:
            'This online tool allows you to generate the MD5 hash of any string.',
        css: {'md5.css': 'md5.css'},
        globalCss: false,
        js: {'md5.js': 'md5.js', 'index.js': 'index.js'},
        globalJs: false,
        date: '2018-07-01',
    },
    {
        slug: 'mp3player',
        name: 'Mp3 Player',
        description: 'Odtwarzacz muzyki',
        css: {'mp3player.css': 'mp3player.css'},
        globalCss: false,
        js: {'mp3player.js': 'mp3player.js'},
        globalJs: false,
        date: '2015-11-19',
    },
    {
        slug: 'my-query',
        name: 'myQuery',
        description: 'Mała biblioteka js',
        css: {'myQuery.css': 'myQuery.css'},
        globalCss: false,
        js: {},
        globalJs: false,
        date: '2016-09-19',
    },
    {
        slug: 'photo',
        name: 'Pixel photo',
        description: 'Dodaje efekt łączenia kolorów w większe piksele.',
        css: {'photo.css': 'photo.css'},
        globalCss: false,
        js: {'photo.js': 'photo.js'},
        globalJs: false,
        date: '2015-05-06',
    },
    {
        slug: 'photoeditor',
        name: 'Edytor zdjęć',
        description: 'Dodaje filtry do zdjęcia.',
        css: {'photoeditor.css': 'photoeditor.css'},
        globalCss: false,
        js: {
            'colorpicker.js': 'colorpicker.js',
            'photo.filter.mask.js': 'photo.filter.mask.js',
            'photoeditor.js': 'photoeditor.js',
        },
        globalJs: true,
        date: '2016-03-10',
    },
    {
        slug: 'photofilter',
        name: 'Photo filter',
        description: 'Dodaje filtry do zdjęcia.',
        css: {'photofilter.css': 'photofilter.css'},
        globalCss: false,
        js: {
            'colorPicker.js': 'colorPicker.js',
            'photo.filter.mask.js': 'photo.filter.mask.js',
            'photo.filter.js': 'photo.filter.js',
        },
        globalJs: true,
        date: '2015-05-04',
    },
    {
        slug: 'plot',
        name: 'Wykresy ',
        description: 'Aplikacja do rysowania wykresu funkcji.',
        css: {'plot.css': 'plot.css'},
        globalCss: true,
        js: {'math.js': 'math.js'},
        globalJs: false,
        date: '2015-05-27',
    },
    {
        slug: 'puzzles',
        name: 'Puzzle',
        description: 'Układaj puzzle z własnych zdjęć',
        css: {'puzzles.css': 'puzzles.css'},
        globalCss: true,
        js: {'puzzles.js': 'puzzles.js'},
        globalJs: true,
        date: '2015-05-14',
    },
    {
        slug: 'record',
        name: 'Record',
        description: 'Nagrywanie filmu z elementu canvas',
        css: {'record.css': 'record.css'},
        globalCss: false,
        js: {'record.js': 'record.js', 'demoRecord.js': 'demoRecord.js'},
        globalJs: false,
        date: '2015-11-12',
    },
    {
        slug: 'rock-paper-scissors',
        name: 'Kamień papier nożyce',
        description: 'Kamień papier nożyce',
        css: {'rock-paper-scissors.css': 'rock-paper-scissors.css'},
        globalCss: false,
        js: {'rock-paper-scissors.js': 'rock-paper-scissors.js'},
        globalJs: false,
        date: '2017-07-20',
    },
    {
        slug: 'rubikscube',
        name: 'Kostka rubika',
        description: '',
        css: {'rubikscube.css': 'rubikscube.css'},
        globalCss: false,
        js: {'rubikscube.js': 'rubikscube.js'},
        globalJs: false,
        date: '2016-03-16',
    },
    {
        slug: 'run',
        name: 'Run calculator',
        description: 'Calculate speed, pace, distance and time',
        css: {'bootstrap.min.css': 'bootstrap.min.css', 'run.css': 'run.css'},
        globalCss: false,
        js: {'run.js': 'run.js'},
        globalJs: false,
        date: '2017-06-07',
    },
    {
        slug: 'runner',
        name: 'Runner',
        description: 'Runner animation',
        css: {'runner.css': 'runner.css'},
        globalCss: false,
        js: {},
        globalJs: false,
        date: '2018-12-27',
    },
    {
        slug: 'squash',
        name: 'Squash',
        description: 'Squash',
        css: {'squash.css': 'squash.css'},
        globalCss: false,
        js: {'squash.js': 'squash.js'},
        globalJs: false,
        date: '2015-05-21',
    },
    {
        slug: 'stayalive',
        name: 'Stay Alive',
        description: 'Ruszaj piłką i unikaj min',
        css: {'stayalive.css': 'stayalive.css'},
        globalCss: false,
        js: {
            'buzz.min.js': 'buzz.min.js',
            'CanvasCurve.js': 'CanvasCurve.js',
            'StayAlive.js': 'StayAlive.js',
        },
        globalJs: true,
        date: '2014-11-12',
    },
    {
        slug: 'sync',
        name: 'Sync',
        description: '-',
        css: {'sync.css': 'sync.css'},
        globalCss: false,
        js: {'sync.js': 'sync.js'},
        globalJs: false,
        date: '2016-06-29',
    },
    {
        slug: 'temp',
        name: 'Tenperatura',
        description: 'Temperaturę na ziemi w zależności od parametrów.',
        css: {'temp.css': 'temp.css'},
        globalCss: false,
        js: {
            'setting.js': 'setting.js',
            'engine.js': 'engine.js',
            'draw.js': 'draw.js',
            'event.js': 'event.js',
            'main.js': 'main.js',
        },
        globalJs: false,
        date: '2014-06-12',
    },
    {
        slug: 'test',
        name: 'Test',
        description: 'Test',
        css: {'test.css': 'test.css'},
        globalCss: false,
        js: {'test.js': 'test.js'},
        globalJs: true,
        date: '2015-05-20',
    },
    {
        slug: 'tetris',
        name: 'Tetris',
        description: 'Tetris',
        css: {'style.css': 'style.css'},
        globalCss: true,
        js: {'tetris.js': 'tetris.js'},
        globalJs: false,
        date: '2015-05-21',
    },
    {
        slug: 'text',
        name: 'Text Statistics',
        description: 'Text Statistics',
        css: {'text.css': 'text.css'},
        globalCss: false,
        js: {'text.js': 'text.js'},
        globalJs: false,
        date: '2017-06-16',
    },
    {
        slug: 'visualizer',
        name: 'Visualiser 3D',
        description: 'Audio visualizer 3D',
        css: {'visualizer.css': 'visualizer.css'},
        globalCss: false,
        js: {
            'object3d.js': 'object3d.js',
            'canvas3d.js': 'canvas3d.js',
            'visualizer.js': 'visualizer.js',
        },
        globalJs: true,
        date: '2016-09-20',
    },
];
